remote_theme: hydecorp/hydejack@v9.0.5

plugins:
  - jekyll-include-cache

menu:
  - title: Start
    url: /start
  - title: API
    url: /api
  - title: Guide
    url: /guide
  - title: Assertions
    url: /assertions
