remote_theme: hydecorp/hydejack@v9.0.5

plugins:
  - jekyll-include-cache

menu:
  - title: Quick Start
    url: /index
  - title: Guide
    url: /guide
  - title: Server API
    url: /api
  - title: Assertions
    url: /assertions
