remote_theme: pmarsceill/just-the-docs
title: Behave
description: An HTTP Mocking server with brains

search_enabled: true

aux_links:
  "GitHub":
    - "//github.com/sayjava/behave"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
