name: Docs
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: sayjava/behave
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn && yarn build:docs
        BUILD_DIR: docs/.vuepress/dist/
